### ISSUE TITLE
None returned from `remoteUpload`

### ISSUE THREAD

**Issue by horkko** [bfrgoncalves/Online-PhyloViZ#3]
Hi guys,

I've been playing with you python script to upload some data online to PhyloViz.net.
I've registered OK. However, when I try upload some data online, I get an error from `remoteUpload.py`:

```
Traceback (most recent call last):
  File "/opt/bigsdb/remoteUpload.py", line 126, in <module>
    main()
Output: Checking if dataset name exists...

  File "/opt/bigsdb/remoteUpload.py", line 32, in main
    rungoeBURST(args, dataset['datasetID'], currentRoot)
```

It looks like `output` is not returned from `remoteUpload` method, so `None` is set into `output` variable (line 30).

I've changed the script and added (line 110) `return output` and the error disappeared and I've been able to load data to PhyloViz Online.

Can you have a look?
Thanks

Emmanuel

**Comment by bfrgoncalves** [comment]
Hi Emmanuel,

You are completely right and you made the right modifications. At the time
I made some changes in the developer branch and I forgot to update the
master. I have pushed the correct version now if you want to use it. Tell
me if you need anything else.

Best regards,

Bruno

2016-07-01 14:48 GMT+01:00 Emmanuel Quevillon <notifications@github.com>:
